[package]
name = "bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
evm = "0.37.0"
hex = "0.4.3"
primitive-types = "0.12.1"
# kindelia = "0.1.5"
